# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: FileTransform@1
  displayName: 'Replace tokens in appsettings.json'
  inputs:
    folderPath: '$(build.sourcesdirectory)/src/MyHealth.Web'
    fileType: 'json'
    targetFiles: 'appsettings.json'

- task: DockerCompose@0
  displayName: 'Run services'
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial(eb33151c-97b2-47a9-9685-fc5d80b4fc4a)'
    azureContainerRegistry: '{"loginServer":"mytestacr2023.azurecr.io", "id" : "/subscriptions/eb33151c-97b2-47a9-9685-fc5d80b4fc4a/resourceGroups/akstestrg/providers/Microsoft.ContainerRegistry/registries/mytestacr2023"}'
    dockerComposeFile: 'docker-compose.ci.build.yml'
    action: 'Run services'
    detached: false

- task: DockerCompose@0
  displayName: 'Build services'
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial(eb33151c-97b2-47a9-9685-fc5d80b4fc4a)'
    azureContainerRegistry: '{"loginServer":"mytestacr2023.azurecr.io", "id" : "/subscriptions/eb33151c-97b2-47a9-9685-fc5d80b4fc4a/resourceGroups/akstestrg/providers/Microsoft.ContainerRegistry/registries/mytestacr2023"}'
    dockerComposeFile: 'docker-compose.yml'
    dockerComposeFileArgs: 'DOCKER_BUILD_SOURCE='
    action: 'Build services'
    additionalImageTags: '$(Build.BuildId)'

- task: DockerCompose@0
  displayName: 'Push services'
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial(eb33151c-97b2-47a9-9685-fc5d80b4fc4a)'
    azureContainerRegistry: '{"loginServer":"mytestacr2023.azurecr.io", "id" : "/subscriptions/eb33151c-97b2-47a9-9685-fc5d80b4fc4a/resourceGroups/akstestrg/providers/Microsoft.ContainerRegistry/registries/mytestacr2023"}'
    dockerComposeFile: 'docker-compose.yml'
    dockerComposeFileArgs: 'DOCKER_BUILD_SOURCE='
    action: 'Push services'
    additionalImageTags: '$(Build.BuildId)'

- task: DockerCompose@0
  displayName: 'Lock services'
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial(eb33151c-97b2-47a9-9685-fc5d80b4fc4a)'
    azureContainerRegistry: '{"loginServer":"mytestacr2023.azurecr.io", "id" : "/subscriptions/eb33151c-97b2-47a9-9685-fc5d80b4fc4a/resourceGroups/akstestrg/providers/Microsoft.ContainerRegistry/registries/mytestacr2023"}'
    dockerComposeFile: 'docker-compose.yml'
    dockerComposeFileArgs: 'DOCKER_BUILD_SOURCE='
    action: 'Lock services'
    outputDockerComposeFile: '$(Build.StagingDirectory)/docker-compose.yml'

- task: CopyFiles@2
  displayName: 'Copy Files'
  inputs:
    Contents: |
     **/mhc-aks.yaml
     **/*.dacpac
     
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    ArtifactName: deploy