version: '3'

services:
  web:
    build: src/MyHealth.Web
    ports:
      - 80:80
    image: sriramdasbalaji/aspnetcore1.0:1.0.4
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./MHC_ASPNetCore.sln && dotnet publish ./MHC_ASPNetCore.sln -c Release -o ./obj/Docker/publish"
